package com.stefanini.model;
// Generated 07/11/2016 12:17:14 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Modelo generated by hbm2java
 */
@Entity
@Table(name = "modelo", catalog = "hackaton")
public class Modelo implements java.io.Serializable {
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idModelo", unique = true, nullable = false)
	private Integer idModelo;
	
	@Column(name = "descricaoModelo", length = 50)
	private String descricaoModelo;
	
	@ManyToOne()
	@JoinColumn(name = "idCategoria")
	private Categoria categoria = new Categoria();

	public Modelo() {
	}

	public Modelo(Integer idModelo, String descricaoModelo, Categoria categoria) {
		//super();
		this.idModelo = idModelo;
		this.descricaoModelo = descricaoModelo;
		this.categoria = categoria;
	}

	public Categoria getCategoria() {
		return categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	
	public Integer getIdModelo() {
		return this.idModelo;
	}

	public void setIdModelo(Integer idModelo) {
		this.idModelo = idModelo;
	}

	
	public String getDescricaoModelo() {
		return this.descricaoModelo;
	}

	public void setDescricaoModelo(String descricaoModelo) {
		this.descricaoModelo = descricaoModelo;
	}

}